"use client";

import { ShieldCheck, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { NativeSelect } from "@/components/ui/native-select";
import { Field } from "@/components/crm/field";
import type { MemberRole, TeamAudit, Workspace, WorkspaceInvite, WorkspaceMember } from "@/lib/crm-types";

const names: Record<MemberRole,string> = { superadmin: "Superadministrador", admin: "Administrador", member: "Membro", reader: "Leitor" };
export function TeamManagement({ workspace, members, invites, audit, role, userId, email, inviteEmail, inviteRole, setInviteEmail, setInviteRole, onInvite, onChangeRole, onRemove, onRevoke, busy, demo }: {
  workspace: Workspace; members: WorkspaceMember[]; invites: WorkspaceInvite[]; audit: TeamAudit[]; role: MemberRole;
  userId: string; email: string; inviteEmail: string; inviteRole: MemberRole; setInviteEmail: (email:string)=>void; setInviteRole: (role:MemberRole)=>void;
  onInvite: ()=>void; onChangeRole: (id:string,role:MemberRole)=>void; onRemove: (id:string)=>void; onRevoke: (id:string)=>void; busy:boolean; demo:boolean;
}) {
  const admin = role === "superadmin" || role === "admin";
  const actorName = (actorId: string | null) => members.find((member) => member.user_id === actorId)?.display_name || members.find((member) => member.user_id === actorId)?.email || (actorId === userId ? "Você" : "Usuário da equipe");
  return <div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]">
    <section className="space-y-5 rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><span className="rounded-xl bg-[#f4ead6] p-3 text-[#173052]"><ShieldCheck className="size-5" /></span><div><h2 className="text-lg font-semibold text-[#10233f]">{workspace.name}</h2><p className="mt-1 text-sm text-slate-600">Contatos, oportunidades e atividades são compartilhados com esta equipe.</p><p className="mt-2 text-sm text-slate-700">Seu acesso: {email || "Acesso local"} · <strong>{names[role]}</strong></p></div></div>
      <div><h3 className="mb-3 font-semibold text-[#10233f]">Membros ({members.length})</h3><div className="divide-y divide-slate-100 rounded-lg border border-slate-200">{members.map((member) => <div key={member.user_id} className="flex flex-wrap items-center gap-3 p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-[#10233f]">{member.display_name || member.email || "Membro"}{member.user_id === userId ? " · Você" : ""}</p><p className="truncate text-xs text-slate-500">{member.email || ""} · {names[member.role]}</p></div>{admin && member.user_id !== userId && <><NativeSelect aria-label={`Papel de ${member.display_name || member.email}`} className="w-44" value={member.role} disabled={busy || demo} onChange={(e) => onChangeRole(member.user_id,e.target.value as MemberRole)}>{Object.entries(names).filter(([value]) => role === "superadmin" || (value !== "superadmin" && value !== "admin")).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</NativeSelect><Button size="sm" variant="ghost" disabled={busy || demo} className="text-rose-700" onClick={() => onRemove(member.user_id)}>Remover</Button></>}</div>)}</div></div>
    </section>
    <div className="space-y-5">{admin && <section className="rounded-xl border border-[#eadbb9] bg-[#fffdfa] p-5 sm:p-6"><UserPlus className="size-6 text-[#a8864b]" /><h3 className="mt-3 font-semibold text-[#10233f]">Convidar usuário</h3><p className="mt-1 text-sm text-slate-600">Convites valem sete dias e são vinculados ao e-mail informado.</p><form onSubmit={(e) => { e.preventDefault(); onInvite(); }} className="mt-4 space-y-3"><Field label="E-mail"><Input required type="email" value={inviteEmail} disabled={demo} onChange={(e) => setInviteEmail(e.target.value)} placeholder="nome@empresa.com" /></Field><Field label="Papel"><NativeSelect value={inviteRole} disabled={demo} onChange={(e) => setInviteRole(e.target.value as MemberRole)}>{Object.entries(names).filter(([value]) => role === "superadmin" || (value !== "superadmin" && value !== "admin")).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</NativeSelect></Field><Button type="submit" disabled={busy || demo} className="bg-[#173052] text-white">Gerar convite</Button></form>{demo && <p className="mt-3 text-sm text-amber-800">Conecte o Supabase para criar usuários e compartilhar os dados entre dispositivos.</p>}</section>}
      {admin && !demo && <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-semibold text-[#10233f]">Convites</h3>{invites.length === 0 ? <p className="mt-3 text-sm text-slate-500">Nenhum convite criado.</p> : <div className="mt-3 divide-y divide-slate-100">{invites.map((invite) => <div key={invite.id} className="flex items-center gap-2 py-2 text-sm"><div className="min-w-0 flex-1"><p className="truncate font-medium">{invite.invitee_email}</p><p className="text-xs text-slate-500">{names[invite.role]} · {invite.used_at ? "Aceito" : invite.revoked_at ? "Revogado" : new Date(invite.expires_at) <= new Date() ? "Expirado" : `Válido até ${new Date(invite.expires_at).toLocaleDateString("pt-BR")}`}</p></div>{!invite.used_at && !invite.revoked_at && new Date(invite.expires_at)>new Date() && <Button size="sm" variant="outline" disabled={busy} onClick={() => onRevoke(invite.id)}>Revogar</Button>}</div>)}</div>}</section>}
      {admin && audit.length > 0 && <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-semibold text-[#10233f]">Alterações na equipe</h3><div className="mt-3 space-y-2">{audit.slice(0,8).map((item) => <p key={item.id} className="text-sm text-slate-600">{new Date(item.created_at).toLocaleString("pt-BR")} · {({ role_changed: "Papel alterado", member_removed: "Membro removido", invite_created: "Convite criado", invite_accepted: "Convite aceito", invite_revoked: "Convite revogado" } as Record<string, string>)[item.action] || item.action} por {actorName(item.actor_id)}{item.detail ? ` · ${item.detail}` : ""}</p>)}</div></section>}</div>
  </div>;
}
